services:
  nextjs:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

  db:
    image: postgres:16
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    
  graphql:
    build:
      context: ./graphql-server
    ports:
      - "4000:4000"
      - "5555:5555"
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/mydb
      PORT: 4000
    depends_on:
      - db
    volumes:
      - ./graphql-server/src:/app/src
      - ./graphql-server/prisma:/app/prisma
      - ./graphql-server/package.json:/app/package.json
      - ./graphql-server/tsconfig.json:/app/tsconfig.json
      - ./graphql-server/nest-cli.json:/app/nest-cli.json

volumes:
  postgres-data: